# Generated by Django 5.2.7 on 2025-12-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(help_text='WhatsApp Business Account Phone Number ID from Meta Business Manager', max_length=255, verbose_name='Phone Number ID')),
                ('access_token', models.CharField(help_text='WhatsApp Business API Access Token from Meta for Developers', max_length=500, verbose_name='Access Token')),
                ('api_version', models.CharField(default='v18.0', help_text='WhatsApp API Version (e.g., v18.0, v19.0)', max_length=20, verbose_name='API Version')),
                ('webhook_verify_token', models.CharField(blank=True, help_text='Webhook Verification Token set in Meta developer console', max_length=255, verbose_name='Webhook Verify Token')),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration can be active at a time', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
                'verbose_name_plural': 'WhatsApp Configurations',
                'ordering': ['-created_at'],
            },
        ),
    ]
