# Generated by Django 5.2.15 on 2026-07-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_alter_whatsappconfig_waba_id"),
        ("integrations", "0003_whatsapptemplate_components_and_statuses"),
    ]

    operations = []
