# Generated by Django 5.2.7 on 2025-12-03 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='merchant_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.CharField(max_length=255, verbose_name='business name')),
                ('business_registration_number', models.CharField(blank=True, max_length=255, verbose_name='business registration number')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('webhook_url', models.URLField(blank=True, help_text='URL to send payment notifications to.', verbose_name='webhook URL')),
                ('return_url', models.URLField(blank=True, help_text='URL to redirect customers to after a payment.', verbose_name='return URL')),
                ('is_approved', models.BooleanField(default=False, help_text='Designates whether the merchant is approved and can accept payments.')),
                ('is_active', models.BooleanField(default=True, help_text="Designates whether the merchant's integration is currently active.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
