# Generated by Django 5.2.7 on 2025-12-03 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='tier name')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission rate for this tier.', max_digits=5, verbose_name='commission rate')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agent_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('agent_code', models.CharField(help_text='Unique code identifying the agent.', max_length=20, unique=True, verbose_name='agent code')),
                ('business_name', models.CharField(max_length=255, verbose_name='business name')),
                ('business_address', models.CharField(blank=True, max_length=255, verbose_name='business address')),
                ('business_registration_number', models.CharField(blank=True, max_length=255, verbose_name='business registration number')),
                ('business_registration_document', models.FileField(blank=True, null=True, upload_to='agent_documents/', verbose_name='business registration document')),
                ('proof_of_address_document', models.FileField(blank=True, null=True, upload_to='agent_documents/', verbose_name='proof of address document')),
                ('location', models.CharField(help_text='Physical location or area of operation.', max_length=255, verbose_name='location')),
                ('is_approved', models.BooleanField(default=False, help_text='Designates whether the agent is approved and active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='agents.agenttier')),
            ],
        ),
    ]
