"""
Author: Moreblessing Nyemba +263787211325
Date: 2024-12-09
Description: WhatsApp message template definitions for Ovii.
These templates need to be created and approved in Meta Business Manager.
"""

# Template definitions for WhatsApp Business Cloud API
# These templates must be created and approved in Meta Business Manager before use

WHATSAPP_TEMPLATES = {
    "otp_verification": {
        "name": "otp_verification",
        "category": "AUTHENTICATION",
        "language": "en",
        "description": "OTP verification message for user authentication",
        "structure": {
            "header": None,
            "body": "{{1}} is your Ovii verification code.",
            "footer": None,  # AUTHENTICATION templates cannot have footers per Meta requirements
            "buttons": [
                {
                    "type": "OTP",
                    "otp_type": "COPY_CODE",
                    # Note: 'text' field is auto-generated by Meta based on template language
                }
            ],
        },
        "variables": ["code"],
        "example": {"body_text": [["123456"]]},
    },
    "transaction_received": {
        "name": "transaction_received",
        "category": "MARKETING",
        "language": "en",
        "description": "Notification when user receives money",
        "structure": {
            "header": None,
            "body": "Good news! You have successfully received a payment of {{1}} from {{2}}. Your wallet has been updated and your new balance is {{3}}. For your records, the transaction ID is {{4}}. Thank you for using Ovii!",
            "footer": "Ovii - Your Mobile Wallet",
            "buttons": [],
        },
        # Combined amount with currency to avoid duplicate variables
        "variables": [
            "amount_with_currency",  # e.g., "10.00 USD"
            "sender_name",
            "new_balance_with_currency",  # e.g., "110.00 USD"
            "transaction_id",
        ],
        "example": {
            "body_text": [["10.00 USD", "John Doe", "110.00 USD", "TXN123456"]]
        },
    },
    "transaction_sent": {
        "name": "transaction_sent",
        "category": "MARKETING",
        "language": "en",
        "description": "Notification when user sends money",
        "structure": {
            "header": None,
            "body": "Payment successful! You have sent {{1}} to {{2}}. Your transaction has been processed and your new balance is {{3}}. For your records, the transaction ID is {{4}}. Thank you for using Ovii!",
            "footer": "Ovii - Your Mobile Wallet",
            "buttons": [],
        },
        # Combined amount with currency to avoid duplicate variables
        "variables": [
            "amount_with_currency",  # e.g., "10.00 USD"
            "recipient_name",
            "new_balance_with_currency",  # e.g., "90.00 USD"
            "transaction_id",
        ],
        "example": {
            "body_text": [["10.00 USD", "Jane Smith", "90.00 USD", "TXN123456"]]
        },
    },
    "welcome_message": {
        "name": "welcome_message",
        "category": "MARKETING",
        "language": "en",
        "description": "Welcome message for new users",
        "structure": {
            "header": None,
            "body": "Welcome to Ovii, {{1}}! 🎉\n\nYour wallet has been created successfully. You can now:\n• Send and receive money\n• Top up your wallet\n• View transaction history\n\nStart your financial journey with us today!",
            "footer": "Ovii - Your Mobile Wallet",
            "buttons": [],
        },
        "variables": ["user_name"],
        "example": {"body_text": [["John"]]},
    },
    "deposit_confirmed": {
        "name": "deposit_confirmed",
        "category": "MARKETING",
        "language": "en",
        "description": "Notification when deposit is confirmed",
        "structure": {
            "header": None,
            "body": "Great news! We have successfully confirmed your deposit of {{1}}. Your wallet has been credited and your new balance is {{2}}. Transaction ID: {{3}}. Thank you for using Ovii!",
            "footer": "Ovii - Your Mobile Wallet",
            "buttons": [],
        },
        # Combined amount with currency to avoid duplicate variables
        "variables": [
            "amount_with_currency",  # e.g., "50.00 USD"
            "new_balance_with_currency",  # e.g., "150.00 USD"
            "transaction_id",
        ],
        "example": {"body_text": [["50.00 USD", "150.00 USD", "TXN123456"]]},
    },
    "withdrawal_processed": {
        "name": "withdrawal_processed",
        "category": "MARKETING",
        "language": "en",
        "description": "Notification when withdrawal is processed",
        "structure": {
            "header": None,
            "body": "Withdrawal complete! We have successfully processed your withdrawal of {{1}}. Your wallet has been debited and your new balance is {{2}}. Transaction ID: {{3}}. Thank you for using Ovii!",
            "footer": "Ovii - Your Mobile Wallet",
            "buttons": [],
        },
        # Combined amount with currency to avoid duplicate variables
        "variables": [
            "amount_with_currency",  # e.g., "25.00 USD"
            "new_balance_with_currency",  # e.g., "75.00 USD"
            "transaction_id",
        ],
        "example": {"body_text": [["25.00 USD", "75.00 USD", "TXN123456"]]},
    },
    "transaction_failed": {
        "name": "transaction_failed",
        "category": "MARKETING",
        "language": "en",
        "description": "Notification when a transaction fails",
        "structure": {
            "header": None,
            "body": "Your transaction of {{1}} {{2}} has failed.\n\nReason: {{3}}\n\nTransaction ID: {{4}}\n\nYour balance remains unchanged. Please try again or contact support if the issue persists.",
            "footer": "Ovii - Your Mobile Wallet",
            "buttons": [],
        },
        "variables": ["amount", "currency", "reason", "transaction_id"],
        "example": {"body_text": [["50.00", "USD", "Insufficient funds", "TXN123456"]]},
    },
    "deposit_failed": {
        "name": "deposit_failed",
        "category": "MARKETING",
        "language": "en",
        "description": "Notification when a deposit fails",
        "structure": {
            "header": None,
            "body": "Your deposit of {{1}} {{2}} has failed.\n\nReason: {{3}}\n\nTransaction ID: {{4}}\n\nPlease contact support if you need assistance.",
            "footer": "Ovii - Your Mobile Wallet",
            "buttons": [],
        },
        "variables": ["amount", "currency", "reason", "transaction_id"],
        "example": {
            "body_text": [["100.00", "USD", "Payment gateway error", "TXN123456"]]
        },
    },
    "withdrawal_failed": {
        "name": "withdrawal_failed",
        "category": "MARKETING",
        "language": "en",
        "description": "Notification when a withdrawal fails",
        "structure": {
            "header": None,
            "body": "Your withdrawal of {{1}} {{2}} has failed.\n\nReason: {{3}}\n\nTransaction ID: {{4}}\n\nYour balance remains unchanged. Please try again or contact support.",
            "footer": "Ovii - Your Mobile Wallet",
            "buttons": [],
        },
        "variables": ["amount", "currency", "reason", "transaction_id"],
        "example": {
            "body_text": [["75.00", "USD", "External service unavailable", "TXN123456"]]
        },
    },
    "kyc_approved": {
        "name": "kyc_approved",
        "category": "MARKETING",
        "language": "en",
        "description": "Notification when KYC document is approved",
        "structure": {
            "header": None,
            "body": "Congratulations! Your identity verification has been approved. ✅\n\nYour account verification level: {{1}}\n\nYou now have access to additional features and higher transaction limits.",
            "footer": "Ovii - Your Mobile Wallet",
            "buttons": [],
        },
        "variables": ["verification_level"],
        "example": {"body_text": [["Identity Verified"]]},
    },
    "kyc_rejected": {
        "name": "kyc_rejected",
        "category": "MARKETING",
        "language": "en",
        "description": "Notification when KYC document is rejected",
        "structure": {
            "header": None,
            "body": "Your identity verification has been declined.\n\nReason: {{1}}\n\nPlease resubmit your documents ensuring they are:\n• Clear and readable\n• Valid and not expired\n• Match your account information\n\nContact support if you need assistance.",
            "footer": "Ovii - Your Mobile Wallet",
            "buttons": [],
        },
        "variables": ["reason"],
        "example": {"body_text": [["Document image is unclear"]]},
    },
    "referral_bonus_credited": {
        "name": "referral_bonus_credited",
        "category": "MARKETING",
        "language": "en",
        "description": "Notification when referral bonus is credited",
        "structure": {
            "header": None,
            "body": "Great news! 🎉\n\nYou've earned a referral bonus of {{1}}.\n\nNew balance: {{2}}\n\nKeep sharing Ovii with friends to earn more rewards!",
            "footer": "Ovii - Your Mobile Wallet",
            "buttons": [],
        },
        # Combined amount with currency to avoid duplicate variables
        "variables": [
            "bonus_amount_with_currency",  # e.g., "5.00 USD"
            "new_balance_with_currency",  # e.g., "105.00 USD"
        ],
        "example": {"body_text": [["5.00 USD", "105.00 USD"]]},
    },
    "payment_received": {
        "name": "payment_received",
        "category": "MARKETING",
        "language": "en",
        "description": "Notification when merchant receives a payment",
        "structure": {
            "header": None,
            "body": "Excellent news! You have received a payment of {{1}} from {{2}}. Your wallet has been credited and your new balance is {{3}}. For your records, the transaction ID is {{4}}. Thank you for using Ovii!",
            "footer": "Ovii - Your Mobile Wallet",
            "buttons": [],
        },
        # Combined amount with currency to avoid duplicate variables
        "variables": [
            "amount_with_currency",  # e.g., "25.00 USD"
            "customer_name",
            "new_balance_with_currency",  # e.g., "525.00 USD"
            "transaction_id",
        ],
        "example": {
            "body_text": [["25.00 USD", "John Doe", "525.00 USD", "TXN123456"]]
        },
    },
    "payment_sent": {
        "name": "payment_sent",
        "category": "MARKETING",
        "language": "en",
        "description": "Notification when user makes a payment to merchant",
        "structure": {
            "header": None,
            "body": "Payment successful! You have paid {{1}} to {{2}}. Your transaction has been processed and your new balance is {{3}}. Transaction ID: {{4}}. Thank you for using Ovii!",
            "footer": "Ovii - Your Mobile Wallet",
            "buttons": [],
        },
        # Combined amount with currency to avoid duplicate variables
        "variables": [
            "amount_with_currency",  # e.g., "15.00 USD"
            "merchant_name",
            "new_balance_with_currency",  # e.g., "85.00 USD"
            "transaction_id",
        ],
        "example": {
            "body_text": [["15.00 USD", "ABC Store", "85.00 USD", "TXN123456"]]
        },
    },
}


def normalize_language_code(language_code: str) -> str:
    """
    Normalize language code to Meta's expected format.
    Converts short codes like 'en' to full codes like 'en_US'.
    
    Args:
        language_code: Language code (e.g., 'en', 'en_US', 'es')
        
    Returns:
        str: Normalized language code in Meta's format (e.g., 'en_US')
    """
    if not language_code:
        return "en_US"  # Default to English US
    
    # If already has underscore or hyphen, assume it's already formatted
    if "_" in language_code or "-" in language_code:
        # Replace hyphen with underscore for consistency
        return language_code.replace("-", "_")
    
    # Map common language codes to Meta's format
    language_mapping = {
        "en": "en_US",
        "es": "es_ES",
        "fr": "fr_FR",
        "de": "de_DE",
        "pt": "pt_BR",
        "zh": "zh_CN",
    }
    
    return language_mapping.get(language_code.lower(), f"{language_code}_US")


def get_template_structure(template_name: str) -> dict:
    """
    Get the structure of a specific template.

    Args:
        template_name: Name of the template

    Returns:
        dict: Template structure or None if not found
    """
    return WHATSAPP_TEMPLATES.get(template_name)


def get_all_templates() -> dict:
    """
    Get all available WhatsApp templates.

    Returns:
        dict: All template definitions
    """
    return WHATSAPP_TEMPLATES


def format_template_components(template_name: str, variables: dict) -> list:
    """
    Format template components with provided variables.

    Args:
        template_name: Name of the template
        variables: Dictionary of variable names and values

    Returns:
        list: Formatted components for WhatsApp API
    """
    template = WHATSAPP_TEMPLATES.get(template_name)
    if not template:
        raise ValueError(f"Template '{template_name}' not found")

    components = []

    # Build body component with variables
    if template["structure"]["body"]:
        parameters = []
        for var in template["variables"]:
            if var in variables:
                parameters.append({"type": "text", "text": str(variables[var])})

        if parameters:
            components.append({"type": "body", "parameters": parameters})

    return components


def convert_template_to_meta_format(template_name: str) -> dict:
    """
    Convert our internal template format to Meta's Graph API format.
    
    Args:
        template_name: Name of the template to convert
        
    Returns:
        dict: Template in Meta's Graph API format
        
    Raises:
        ValueError: If template is not found
    """
    template = WHATSAPP_TEMPLATES.get(template_name)
    if not template:
        raise ValueError(f"Template '{template_name}' not found")
    
    # Convert language code format (en -> en_US if needed)
    language_code = normalize_language_code(template["language"])
    
    components = []
    structure = template["structure"]
    
    # Check if this is an OTP authentication template (used in multiple places below)
    has_otp_button = any(
        button.get("type") == "OTP" 
        for button in structure.get("buttons", [])
    )
    is_otp_auth_template = template["category"] == "AUTHENTICATION" and has_otp_button
    
    # Add HEADER component if present
    if structure.get("header"):
        components.append({
            "type": "HEADER",
            "format": "TEXT",
            "text": structure["header"]
        })
    
    # Add BODY component (required)
    if structure.get("body"):
        body_component = {
            "type": "BODY"
        }
        
        # For AUTHENTICATION templates with OTP buttons, use add_security_recommendation
        # instead of the text field (Meta API requirement)
        if is_otp_auth_template:
            # For OTP authentication templates, Meta automatically adds security text
            # We only provide the code via add_security_recommendation
            # Meta will auto-generate the body text in the format: "<CODE> is your verification code."
            # The original body text from our template is ignored in this case
            body_component["add_security_recommendation"] = True
        else:
            # For all other templates, include the text field
            body_component["text"] = structure["body"]
        
        # Add example values for variables if present
        if template.get("example") and template["example"].get("body_text"):
            body_component["example"] = {
                "body_text": template["example"]["body_text"]
            }
        
        components.append(body_component)
    
    # Add FOOTER component if present
    # Note: AUTHENTICATION templates cannot have footers per Meta requirements
    if structure.get("footer"):
        if template["category"] == "AUTHENTICATION":
            # Log warning but don't add footer for AUTHENTICATION templates
            # This is a Meta API requirement
            pass
        else:
            components.append({
                "type": "FOOTER",
                "text": structure["footer"]
            })
    
    # Add BUTTONS component if present
    # Note: AUTHENTICATION templates with OTP buttons don't need explicit button components
    # Meta automatically adds the "Copy code" button for OTP authentication templates
    if structure.get("buttons") and len(structure["buttons"]) > 0:
        # Only add BUTTONS component if NOT an OTP authentication template
        if not is_otp_auth_template:
            components.append({
                "type": "BUTTONS",
                "buttons": structure["buttons"]
            })
    
    # Build final payload
    payload = {
        "name": template["name"],
        "category": template["category"],
        "language": language_code,
        "components": components
    }
    
    return payload
