# Generated by Django 5.2.7 on 2025-12-03 14:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oviiuser',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Unique code that this user can share to refer others.', max_length=10, null=True, unique=True, verbose_name='referral code'),
        ),
        migrations.AddField(
            model_name='oviiuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='The user who referred this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(help_text='The referral code that was used.', max_length=10, verbose_name='referral code used')),
                ('referrer_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bonus amount credited to the referrer.', max_digits=10, verbose_name='referrer bonus')),
                ('referred_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bonus amount credited to the referred user.', max_digits=10, verbose_name='referred bonus')),
                ('bonus_status', models.CharField(choices=[('PENDING', 'Pending'), ('CREDITED', 'Credited'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10, verbose_name='bonus status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('referred', models.ForeignKey(help_text='The user who was referred.', on_delete=django.db.models.deletion.CASCADE, related_name='received_referrals', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(help_text='The user who made the referral.', on_delete=django.db.models.deletion.CASCADE, related_name='made_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('referred',), name='unique_referred_user')],
            },
        ),
    ]
