# Generated by Django 5.1.7 on 2025-07-12 22:32

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_otprequest_email_otprequest_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='oviiuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Must be in international format, e.g., +263787211325', max_length=128, region=None, unique=True, verbose_name='phone number'),
        ),
    ]
