# Generated by Django 5.1.7 on 2025-07-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_otprequest_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oviiuser',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='address line 1'),
        ),
        migrations.AddField(
            model_name='oviiuser',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='address line 2'),
        ),
        migrations.AddField(
            model_name='oviiuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='oviiuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='oviiuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='oviiuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20, null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='oviiuser',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID or other official identification number.', max_length=50, null=True, unique=True, verbose_name='national id number'),
        ),
        migrations.AddField(
            model_name='oviiuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='postal code'),
        ),
    ]
